version: "3.1"
services:
  postgres-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: testUser
      POSTGRES_DB: test
    volumes:
      - ./sql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "5432:5432"
  spring-boot-experiment:
    image: mattbriden/spring-experiment-api
    ports:
      - "8090:8080"
    environment:
      DB_USER: testUser
      DB_PASS: password
      DB_URL: jdbc:postgresql://postgres-db:5432/test
  start_db:
    image: dadarek/wait-for-dependencies
    depends_on:
      - "postgres-db"
    command: postgres-db:5432
